name: emoji_app
description: "Generate and copy emojis to clipboard."
publish_to: 'none' 
version: 1.0.0+4

environment:
  sdk: '>=3.5.0 <4.0.0'
  
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  window_manager:
    git: https://github.com/rafaelortizzableh/window_manager
  tray_manager: ^0.3.0
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
  intl: ^0.19.0
  hooks_riverpod: ^2.5.1
  shared_preferences: ^2.2.3
  flutter_hooks: ^0.20.5
  cupertino_icons: ^1.0.6
  flutter_animate: ^4.5.0
  go_router: ^14.2.0
  collection: ^1.18.0
  dio: ^5.5.0+1
  nanoid2: ^2.0.1
  url_launcher: ^6.3.0
  package_info_plus: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^3.0.0

flutter_launcher_icons:  
  macos:
    generate: true
    image_path: "assets/app_icon.png"
  image_path_ios: "assets/mobile_icon.png"
  remove_alpha_ios: true
  ios: true
  android: true
  image_path_android: "assets/mobile_icon.png"
  adaptive_icon_background: "assets/background.png"
  adaptive_icon_foreground: "assets/foreground.png"
  web:
    generate: true
    image_path: "assets/app_icon.png"
    background_color: "#15161B"
    theme_color: "#6A52FF"

  

  


flutter:
  uses-material-design: true

  assets:
    - assets/menu_icon/
    - assets/app_icon.png
