name: emoji_app
description: "Generate and copy emojis to clipboard."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'
  
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  window_manager:
    git: https://github.com/joinbuzz/window_manager
  tray_manager:
    git: https://github.com/joinbuzz/tray_manager
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
  intl: ^0.19.0
  hooks_riverpod: ^2.5.1
  shared_preferences: ^2.2.3
  flutter_hooks: ^0.20.5
  cupertino_icons: ^1.0.6
  flutter_animate: ^4.5.0
  go_router: ^14.2.0
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^3.0.0

flutter_launcher_icons:  
  macos:
    generate: true
    image_path: "assets/app_icon.png"


flutter:
  uses-material-design: true

  assets:
    - assets/menu_icon/
